verifyAttributePresent() method
Umutayb/Pickleib pull request #78
Opened 2023-11-16 13:14 UTC by egecansen

- added method -> new attributePresent() & verifyAttributePresent()
- improved the bundleInteraction() method
- Fixed the unit tests

2023-11-21 15:31 UTC, Umutayb requested changes

2023-11-21 15:31 UTC, Umutayb commented on src/main/java/pickleib/web/utilities/WebUtilities.java
> +            WebElement element) {
Remove unnecessary lines

2023-11-21 15:31 UTC, Umutayb commented on src/main/java/pickleib/web/utilities/WebUtilities.java
> +                return elementAttributes.contains(attributeName);
This does not wait until the attribute is contained, please fix

2023-11-21 15:31 UTC, Umutayb commented on src/main/java/pickleib/web/utilities/WebUtilities.java
> +        log.warning("Element does not contain " +
Unnecessary break

2023-11-21 15:36 UTC, egecansen commented on src/main/java/pickleib/web/utilities/WebUtilities.java
> +                return elementAttributes.contains(attributeName);
done

2023-11-21 15:37 UTC, egecansen commented on src/main/java/pickleib/web/utilities/WebUtilities.java
> +            WebElement element) {
done

2023-11-21 15:37 UTC, egecansen commented on src/main/java/pickleib/web/utilities/WebUtilities.java
> +        log.warning("Element does not contain " +
done

2023-11-21 15:45 UTC, Umutayb requested changes

2023-11-21 15:45 UTC, Umutayb commented on src/main/java/pickleib/web/utilities/WebUtilities.java
> +
Space remains...

2023-11-21 15:45 UTC, Umutayb commented on src/main/java/pickleib/web/utilities/WebUtilities.java
> +                for (String attribute : elementAttributes) return attribute.equals(attributeName);
The method name suggests that the method is supposed to check if an attribute is present, however the returned value is whether this attribute ia equal to certain other value.. 

Please resolve this discrepancy.

2023-11-22 08:28 UTC, egecansen commented
can you check the last updates?

2023-12-19 21:04 UTC, closed without merging